# Generated by Django 5.1.3 on 2026-02-04 06:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('customer', 'Customer'), ('external', 'External')], max_length=20)),
                ('external_ref', models.CharField(blank=True, max_length=120, null=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='open', max_length=20)),
                ('category', models.CharField(choices=[('billing', 'Billing'), ('technical', 'Technical'), ('general', 'General')], default='general', max_length=20)),
                ('customer_id', models.EmailField(blank=True, max_length=254, null=True)),
                ('assigned_to', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'priority'], name='tickets_tic_status_b256f6_idx'), models.Index(fields=['category'], name='tickets_tic_categor_fc7dd1_idx'), models.Index(fields=['assigned_to'], name='tickets_tic_assigne_10250a_idx'), models.Index(fields=['source'], name='tickets_tic_source_f00248_idx'), models.Index(fields=['customer_id'], name='tickets_tic_custome_c66646_idx'), models.Index(fields=['created_at'], name='tickets_tic_created_5dd600_idx')],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=200)),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tickets.ticket')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['ticket', 'created_at'], name='tickets_com_ticket__f8cb69_idx'), models.Index(fields=['role'], name='tickets_com_role_5672dd_idx')],
            },
        ),
    ]
