# Generated by Django 5.1.3 on 2026-02-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_category_ticketattachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(default='general', max_length=50),
        ),
    ]
